#!/usr/bin/with-contenv bash

# update certs for mono
if [[ ! -f "/app/duplicati/donecerts" ]]; then
	echo "*** Running mono cert sync ***"
	cert-sync --quiet /etc/ssl/certs/ca-certificates.crt
	touch "/app/duplicati/donecerts"
fi

# permissions
chown -R abc:abc \
	/config