#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 8200" \
        cd /app/duplicati s6-setuidgid abc \
            mono Duplicati.Server.exe \
                --webservice-interface=any \
                --server-datafolder=/config \
                --webservice-allowed-hostnames=* \
                "$CLI_ARGS"
